name: PHPUnit (php-actions)

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: php-actions/composer@v6

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        env:
          TEST_NAME: Scarlett
        with:
          version: 'composer'
          php_version: 8.3
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

      - name: Run PHPUnit Tests with Coverage
        run: vendor/bin/phpunit --coverage-text --coverage-html=_coverage