name: PHPUnit (php-actions)

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: Run PHPUnit Tests with Coverage
        run: vendor/bin/phpunit --coverage-text --coverage-html=_coverage