name: PHPUnit (php-actions)

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        env:
          TEST_NAME: Scarlett
        with:
          version: 'composer'
          php_version: 8.3
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text